#!/bin/sh

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".jsx\{0,1\}$")

ESLINT="$(git rev-parse --show-toplevel)/node_modules/.bin/eslint"

if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

PASS=true

echo "\n开始检查代码:\n"

# Check for eslint
which eslint &> /dev/null
# if [[ "$?" == 1 ]]; then
#   echo "\t\033[41mPlease install ESlint\033[0m"
#   exit 1
# fi

if [[ ! -x "$ESLINT" ]]; then
  echo "\t\033[41mPlease install ESlint\033[0m (npm i --save --save-exact --dev eslint)"
  exit 1
fi

# for FILE in $STAGED_FILES
# do
#   # eslint "$FILE"  --ext .js,.jsx src

#   # echo $FILE
#   # echo "-----"
#   npm run lint

#   if [[ "$?" == 0 ]]; then
#     echo "\t\033[32mESLint Passed: $FILE\033[0m"
#     echo "——————————"
#   else
#     echo "\t\033[41mESLint Failed: $FILE\033[0m"
#     PASS=false
#   fi
# done

npm run lint
if [[ "$?" == 0 ]]; then
  echo "OK"
else
  echo "Error"
  PASS=false
fi

echo "\n代码检查完毕!\n"

if ! $PASS; then
  echo "\033[41mCOMMIT FAILED:\033[0m 你的代码不符合ESLint规范，请检查代码后再执行提交.\n"
  exit 1
else
  echo "\033[42mCOMMIT SUCCEEDED\033[0m\n"
fi

exit $?